---
name: "jellyfin-plugin-streamlink"
guid: "87c22ffb-736c-41aa-8a2d-95d46977bb26"
version: "1.0.0"
targetAbi: "10.6.0.0"
owner: "jellyfin"
nicename: "Streamlink"
description: "Watching channels through Streamlink on LiveTV"
overview: >
  Watch live streams through Jellyfin using Streamlink: https://github.com/streamlink/streamlink
category: "LiveTV"
artifacts:
  - "Jellyfin.Plugin.Streamlink.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
